[package]
name = "rusty-journal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
home = "0.5.9"
serde_json = "1.0.114"
structopt = "0.3.26"

[dependencies.chrono]
features = ["serde"]
version = "0.4.35"

[dependencies.serde]
features = ["derive"]
version = "1.0.197"